resilience4j.retry:
  instances:
    default:
      maxAttempts: 3 # if @Retry annotated method call fails, this app will try 2 times to call the api
      waitDuration: 1s  #wait time after failure to wait for next call
      enableExponentialBackoff: true  #wait duration will keep increasing after failure

#for more info ,Please have a look into documentation- https://resilience4j.readme.io/docs/circuitbreaker
resilience4j.circuitbreaker:
  instances:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 50
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 60s
      failureRateThreshold: 40

resilience4j.bulkhead:
  instances:
    default:
      maxConcurrentCalls: 10
      maxWaitDuration: 10ms

resilience4j.ratelimiter:
  instances:
    default:
      limitForPeriod: 10
      timeoutDuration: 0
      limitRefreshPeriod: 500ms
      registerHealthIndicator: true
      eventConsumerBufferSize: 100

resilience4j.timelimiter:
  instances:
    default:
      timeoutDuration: 2s
      cancelRunningFuture: true
